DROP TABLE IF EXISTS Kohde CASCADE;
DROP TABLE IF EXISTS Veto CASCADE;
DROP TABLE IF EXISTS Vedonlyoja CASCADE;
DROP TABLE IF EXISTS Laji CASCADE;
DROP TABLE IF EXISTS Ehdotus CASCADE;
DROP TABLE IF EXISTS Valinta CASCADE;
