DROP TABLE IF EXISTS Veto CASCADE;
DROP TABLE IF EXISTS Vedonlyoja CASCADE;
DROP TABLE IF EXISTS Admin CASCADE;
DROP TABLE IF EXISTS Sport CASCADE;
DROP TABLE IF EXISTS Competition CASCADE;
DROP TABLE IF EXISTS Laji CASCADE;
DROP TABLE IF EXISTS Kilpailu CASCADE;
